sudo: required
services:
  - docker
env:
  - IMAGE_ARCH=i386
  - IMAGE_ARCH=amd64
  - IMAGE_ARCH=arm32v7
  - IMAGE_ARCH=arm64v8

install:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - |
    IMAGE_NAME=bird-lg

    # Translate to alternative arch names used in multiarch images
    if [ "$IMAGE_ARCH" == "amd64"   ]; then IMAGE_ARCH_ALT=amd64  ; fi
    if [ "$IMAGE_ARCH" == "i386"    ]; then IMAGE_ARCH_ALT=i386   ; fi
    if [ "$IMAGE_ARCH" == "arm32v7" ]; then IMAGE_ARCH_ALT=armhf  ; fi
    if [ "$IMAGE_ARCH" == "arm64v8" ]; then IMAGE_ARCH_ALT=aarch64; fi

    # Build image
    docker build \
      -t $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_ARCH \
      --build-arg IMAGE_ARCH=$IMAGE_ARCH \
      --build-arg IMAGE_ARCH_ALT=$IMAGE_ARCH_ALT \
      .

    # Tag image :{arch} and :{arch}-build{build number}
    docker tag $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_ARCH $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_ARCH-build$TRAVIS_BUILD_NUMBER
    if [ "$IMAGE_ARCH" = "amd64" ]; then
      # Tag as latest for amd64 images
      docker tag $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_ARCH $DOCKER_USERNAME/$IMAGE_NAME:latest
      docker tag $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_ARCH $DOCKER_USERNAME/$IMAGE_NAME:build$TRAVIS_BUILD_NUMBER
    fi
  - docker push $DOCKER_USERNAME/$IMAGE_NAME
